# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8f3c4dff220576e71648ee20f5b4cce0db36910caff0ad83bd70680fbff58cf92bbea086c5d6f5f5cec7e88235c0dd805a3d3872a8a0f41bf9401d812e485ae

test:
  secret_key_base: 3599188ee87be0f2966c613629618f528728dc55b2e5e8e3a72ebcaafdb56bf613e3b518760a1f1231fab34543a37a613645b93007f87a27725e389fa4afd890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
